import os
import uuid

MONGODB_URI = os.getenv("MONGODB_URI", "YOUR_MONGODB_URI")
MONGODB_DATABASE = os.getenv("MONGODB_DATABASE", "YOUR_DATABASE")

TIMEOUT_MS = 30000  # 30초
MAX_CONCURRENCY = 40
USER_AGENT = "GovStatusBot/1.0"

NAMESPACE_AGENCY = uuid.uuid5(uuid.NAMESPACE_DNS, "gov-status")
