import os

MONGODB_URI = os.getenv("MONGODB_URI", "YOUR_MONGODB_URI")
MONGODB_DATABASE = os.getenv("MONGODB_DATABASE", "YOUR_DATABASE")

TIMEOUT_THRESHOLD = 30000  # 30초
USER_AGENT = "GovStatusBot/1.0"
