name: Crawl and Update MongoDB

on:
  workflow_dispatch:
  schedule:
    - cron: "*/8 * * * *"   # 10분 간격: 8분 간격 + 프로그램 실행 약 1.25분 + github actions 실행 대기 α분

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" 

      - name: Install dependencies
        run: pip install -r tasks/requirements.txt

      - name: Run crawler
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        run: |
          python tasks/main.py