name: Crawl and Update MongoDB

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # 10분 간격 (UTC 기준): 데이터 수집 및 저징 5분 + 5분마다 github actions 실행 = 1회 당 10분    # 추후 크롤러 개선 시 10분으로 변경 필요

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" 

      - name: Install dependencies
        run: pip install -r tasks/requirements.txt

      - name: Run crawler
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        run: |
          python tasks/main.py || echo "⚠️ Script failed, skipping..."